services:
  atlas_db:
    image: 'postgres:latest'
    environment:
        - POSTGRES_DB=atlas_db
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5434:5434"

  atlas:
    build:
      context: .
    ports:
      - "8085:8085"
    depends_on:
      - atlas_db
    env_file:
      - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://atlas_db:5432/atlas_db
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
