CREATE TYPE rotulo AS ENUM (
    'LEITE', 'OVO', 'PEIXES', 'CEREAIS', 'GLUTEN', 'CRUSTACEOS',
    'SOJA', 'AMENDOA', 'AVELA', 'CASTANHA', 'NOZES', 'PISTACHE'
);

CREATE TYPE medida AS ENUM (
    'MILIGRAMA', 'GRAMA', 'KILOGRAMA', 'MILILITRO', 'LITRO', 'UNIDADE'
);

CREATE TYPE tag AS ENUM (
    'BEBIDA', 'COMIDA', 'OUTROS'
);
